In [1]:
import neural_net as nn
import numpy as np

In [2]:
weights = nn.initialize_network(2, 1, 2, 2)
print(weights)
# print(np.array(weights))

[array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471]]), array([[-2.42667924, -0.42891263]])]


In [3]:
#Confusion matrix
instrs = ["guitar", "clarinet", "flute", "saxophone", "violin"]

def confusion_matrix (actual, desired, outp_length):
    """Gets confusion matrix for a networks output."""
    confusion = np.zeros((outp_length, outp_length))
    for indx in range(len(actual)):
        # print(desired[indx])
        i = desired[indx].tolist().index(1)
        # print(actual[indx])
        j = actual[indx].argmax()
        confusion[i][j] += 1
    return confusion

def print_cc_info(cc, data_length, categories):
    sum1, sum2 = 0, 0
    class_list = []
    for i in range(len(cc)):
        for j in range(len(cc[i])):
            if j == i: 
                sum1 += cc[i][j]
                class_list.append(cc[i][j])
            sum2 += cc[i][j]
    print("This NN got correct ", sum1, " out of ", sum2, " tests")
    print("which is ", str(sum1/sum2)[:5])
    for i in range(len(categories)):
        print("For", categories[i], ", This NN classified", class_list[i], " out of ", data_length)
        print("which is ", str(class_list[i]/data_length)[:5])

Testing the neural network on the data from ps6. Looks like it does pretty well!

In [4]:
def load_data(filename):
    data = np.loadtxt(filename,delimiter=',')
    inputs = []
    outputs = []
    for line in data:
        inputs.append(line[:-1])
        output = [0] * 10
        output[int(line[-1])] = 1
        outputs.append(output)
    return (np.array(inputs), np.array(outputs))

(test_inp, test_out) = load_data("data/optdigits.tra")

nn.initialize_network(test_inp.T.shape[0], test_out.T.shape[0], 2, 10)
nn.train_network(test_inp.T, test_out.T, nn.update_weights, 50, 0.01)
actual = nn.predict_network(test_inp.T, nn.logistic)
cc = confusion_matrix(actual.T, test_out, test_out.T.shape[0])
print(cc)




Iteration:  0
Iteration:  1
Iteration:  2
Iteration:  3
Iteration:  4
Iteration:  5
Iteration:  6
Iteration:  7
Iteration:  8
Iteration:  9
Iteration:  10
Iteration:  11
Iteration:  12
Iteration:  13
Iteration:  14
Iteration:  15
Iteration:  16
Iteration:  17
Iteration:  18
Iteration:  19
Iteration:  20
Iteration:  21
Iteration:  22
Iteration:  23
Iteration:  24
Iteration:  25
Iteration:  26
Iteration:  27
Iteration:  28
Iteration:  29
Iteration:  30
Iteration:  31
Iteration:  32
Iteration:  33
Iteration:  34
Iteration:  35
Iteration:  36
Iteration:  37
Iteration:  38
Iteration:  39
Iteration:  40
Iteration:  41
Iteration:  42
Iteration:  43
Iteration:  44
Iteration:  45
Iteration:  46
Iteration:  47
Iteration:  48
Iteration:  49
[[ 370.    0.    0.    0.    1.    0.    1.    0.    0.    4.]
 [   0.  189.   21.  143.    5.   11.    0.    2.   14.    4.]
 [   4.    0.  343.   15.    0.    0.    0.    1.    8.    9.]
 [   0.    5.    9.  284.    0.   48.    0.   17.    3.   23.]
 [   0. 

Testing the neural network on the harmonic information. Looks like it can classify guitars pretty well based on the harmonic information, but not very well for the other instruments. 

In [5]:
h_data = []
instrs = ["guitar", "clarinet", "flute", "saxophone", "violin"]
ind = 0
for instr in instrs:
    h_data.append([])
    infile = open("reps/" + instr + "_harmonics.txt", 'r')
    for line in infile:
        ex = []
        for i in line.split(','):
            ex.append( float(i.strip()) )
        h_data[ind].append(ex)
    ind += 1
        
#print(h_data)
h_inp = []
h_outputs = []
for i in range(50):
    for j in range(5):
        h_output = [0]*5
        h_output[j] = 1
        h_outputs.append(h_output)
        h_inp.append(np.array(h_data[j][i]))

h_inp = np.array(h_inp)
h_out = np.array(h_outputs)

nn.initialize_network(h_inp.T.shape[0], h_out.T.shape[0], 2, 5)
nn.train_network(h_inp.T, h_out.T, nn.update_weights, 200, 0.01)
real = nn.predict_network(h_inp.T, nn.logistic)
cm = confusion_matrix(real.T, h_out, h_out.T.shape[0])
print(cm)
print_cc_info(cm, 50, instrs)

Iteration:  0
Iteration:  1
Iteration:  2
Iteration:  3
Iteration:  4
Iteration:  5
Iteration:  6
Iteration:  7
Iteration:  8
Iteration:  9
Iteration:  10
Iteration:  11
Iteration:  12
Iteration:  13
Iteration:  14
Iteration:  15
Iteration:  16
Iteration:  17
Iteration:  18
Iteration:  19
Iteration:  20
Iteration:  21
Iteration:  22
Iteration:  23
Iteration:  24
Iteration:  25
Iteration:  26
Iteration:  27
Iteration:  28
Iteration:  29
Iteration:  30
Iteration:  31
Iteration:  32
Iteration:  33
Iteration:  34
Iteration:  35
Iteration:  36
Iteration:  37
Iteration:  38
Iteration:  39
Iteration:  40
Iteration:  41
Iteration:  42
Iteration:  43
Iteration:  44
Iteration:  45
Iteration:  46
Iteration:  47
Iteration:  48
Iteration:  49
Iteration:  50
Iteration:  51
Iteration:  52
Iteration:  53
Iteration:  54
Iteration:  55
Iteration:  56
Iteration:  57
Iteration:  58
Iteration:  59
Iteration:  60
Iteration:  61
Iteration:  62
Iteration:  63
Iteration:  64
Iteration:  65
Iteration:  66
Itera

Now testing the neural network on the spectral flux. It does decently well, getting around 50% correct across all instruments. It is especially bad at classifying the saxophone (it usually classifies it as a violin), which makes sense given that the spectrum for both instruments looks quite similar (aside from the attack portion of the spectrum). 

In [6]:
f_data = []
instrs = ["guitar", "clarinet", "flute", "saxophone", "violin"]
ind = 0

for instr in instrs:
    f_data.append([])
    infile = open("reps/" + instr + "_flux.txt", 'r')
    for line in infile:
        ex = []
        for i in line.split(','):
            ex.append( float(i.strip()) )
        f_data[ind].append(ex)
    ind += 1

f_inp = []
f_outputs = []
for i in range(50):
    for j in range(5):
        f_output = [0]*5
        f_output[j] = 1
        f_outputs.append(f_output)
        f_inp.append(np.array(f_data[j][i]))

f_inp = np.array(f_inp)
f_out = np.array(f_outputs)

nn.initialize_network(f_inp.T.shape[0], f_out.T.shape[0], 3, 5)
nn.set_hidden_units(1, 10)
nn.train_network(f_inp.T, f_out.T, nn.update_weights, 300, 0.01)
real = nn.predict_network(f_inp.T, nn.logistic)
cm = confusion_matrix(real.T, f_out, f_out.T.shape[0])
print(cm)
print_cc_info(cm, 50, instrs)

Iteration:  0
Iteration:  1
Iteration:  2
Iteration:  3
Iteration:  4
Iteration:  5
Iteration:  6
Iteration:  7
Iteration:  8
Iteration:  9
Iteration:  10
Iteration:  11
Iteration:  12
Iteration:  13
Iteration:  14
Iteration:  15
Iteration:  16
Iteration:  17
Iteration:  18
Iteration:  19
Iteration:  20
Iteration:  21
Iteration:  22
Iteration:  23
Iteration:  24
Iteration:  25
Iteration:  26
Iteration:  27
Iteration:  28
Iteration:  29
Iteration:  30
Iteration:  31
Iteration:  32
Iteration:  33
Iteration:  34
Iteration:  35
Iteration:  36
Iteration:  37
Iteration:  38
Iteration:  39
Iteration:  40
Iteration:  41
Iteration:  42
Iteration:  43
Iteration:  44
Iteration:  45
Iteration:  46
Iteration:  47
Iteration:  48
Iteration:  49
Iteration:  50
Iteration:  51
Iteration:  52
Iteration:  53
Iteration:  54
Iteration:  55
Iteration:  56
Iteration:  57
Iteration:  58
Iteration:  59
Iteration:  60
Iteration:  61
Iteration:  62
Iteration:  63
Iteration:  64
Iteration:  65
Iteration:  66
Itera

/Accounts/mcmillans/Desktop/Final Project/cs328-final/neural_net.py:7: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


Now testing the neural network on the zero-crossing rate and spectral centroid. It does pretty poorly. 

In [7]:
zcr_data = [np.loadtxt("reps/guitar_zcr.txt"), np.loadtxt("reps/clarinet_zcr.txt"), np.loadtxt("reps/flute_zcr.txt"), np.loadtxt("reps/saxophone_zcr.txt"), np.loadtxt("reps/violin_zcr.txt")]
sc_data = [np.loadtxt("reps/guitar_centroid.txt"), np.loadtxt("reps/clarinet_centroid.txt"), np.loadtxt("reps/flute_centroid.txt"), np.loadtxt("reps/saxophone_centroid.txt"), np.loadtxt("reps/violin_centroid.txt")]

zc_inp = []
zc_inputs = []
zc_outputs = []
for i in range(50):
    for j in range(5):
        zc_inputs = []
        zc_output = [0]*5
        zc_inputs.append(sc_data[j][i])
        zc_inputs.append(zcr_data[j][i])
        zc_output[j] = 1
        zc_outputs.append(zc_output)
        zc_inp.append(zc_inputs)

zc_inp = np.array(zc_inp)
print(zc_inp.T)
zc_out = np.array(zc_outputs)
nn.initialize_network(zc_inp.T.shape[0], zc_out.T.shape[0], 2, 5)
nn.train_network(zc_inp.T, zc_out.T, nn.update_weights, 50, 0.01)
real = nn.predict_network(zc_inp.T, nn.logistic)
cm = confusion_matrix(real.T, zc_out, zc_out.T.shape[0])
print(cm)
print_cc_info(cm, 50, instrs)

[[  2.08202749e+03   1.73554663e+03   1.97602863e+03   1.60151005e+03
    1.36138544e+03   2.42029233e+03   2.18245228e+03   1.67608714e+03
    2.55176024e+03   1.76987374e+03   1.15381758e+03   1.09881640e+03
    1.55546014e+03   1.06890645e+03   1.69552931e+03   2.21365041e+03
    1.23196660e+03   2.13037987e+03   1.23270498e+03   1.99909199e+03
    2.23546596e+03   1.97779465e+03   1.48127839e+03   1.68268005e+03
    2.30860338e+03   2.14518952e+03   2.33980374e+03   2.42607709e+03
    2.67964768e+03   1.73802448e+03   2.17768917e+03   1.18921335e+03
    1.80649057e+03   1.14879588e+03   2.01195826e+03   2.35101611e+03
    1.27291322e+03   1.65194509e+03   1.19920426e+03   1.88241297e+03
    1.37311282e+03   2.18715065e+03   2.50926638e+03   1.02669750e+03
    2.17570304e+03   2.18378882e+03   2.49080469e+03   1.66076274e+03
    1.89910487e+03   1.74833418e+03   2.70351049e+03   1.31837545e+03
    2.15650166e+03   2.91546110e+03   2.13170634e+03   2.23098148e+03
    1.45311509e+03  

Testing the neural network on the ratio of spectral centroid to zero-crossing rate. Still does pretty poorly.

In [8]:
r_inp = []
r_inputs = []
r_outputs = []
for i in range(50):
    for j in range(5):
        r_inputs = []
        r_output = [0]*5
        r_inputs.append(sc_data[j][i]/zcr_data[j][i])
        r_output[j] = 1
        r_outputs.append(r_output)
        r_inp.append(r_inputs)

r_inp = np.array(r_inp)
r_out = np.array(r_outputs)
nn.initialize_network(zc_inp.T.shape[0], zc_out.T.shape[0], 2, 5)
nn.train_network(zc_inp.T, zc_out.T, nn.update_weights, 50, 0.01)
real = nn.predict_network(zc_inp.T, nn.logistic)
cm = confusion_matrix(real.T, zc_out, zc_out.T.shape[0])
print(cm)
print_cc_info(cm, 50, instrs)

Iteration:  0
Iteration:  1
Iteration:  2
Iteration:  3
Iteration:  4
Iteration:  5
Iteration:  6
Iteration:  7
Iteration:  8
Iteration:  9
Iteration:  10
Iteration:  11
Iteration:  12
Iteration:  13
Iteration:  14
Iteration:  15
Iteration:  16
Iteration:  17
Iteration:  18
Iteration:  19
Iteration:  20
Iteration:  21
Iteration:  22
Iteration:  23
Iteration:  24
Iteration:  25
Iteration:  26
Iteration:  27
Iteration:  28
Iteration:  29
Iteration:  30
Iteration:  31
Iteration:  32
Iteration:  33
Iteration:  34
Iteration:  35
Iteration:  36
Iteration:  37
Iteration:  38
Iteration:  39
Iteration:  40
Iteration:  41
Iteration:  42
Iteration:  43
Iteration:  44
Iteration:  45
Iteration:  46
Iteration:  47
Iteration:  48
Iteration:  49
[[  0.   0.   0.   0.  50.]
 [  0.   0.   0.   0.  50.]
 [  0.   0.   0.   0.  50.]
 [  0.   0.   0.   0.  50.]
 [  0.   0.   0.   0.  50.]]
This NN got correct  50.0  out of  250.0  tests
which is  0.2
For guitar , This NN classified 0.0  out of  50
which is 

In [9]:
fund_data = [np.loadtxt("reps/guitar_funds.txt"), np.loadtxt("reps/clarinet_funds.txt"), np.loadtxt("reps/flute_funds.txt"), np.loadtxt("reps/saxophone_funds.txt"), np.loadtxt("reps/violin_funds.txt")]
sc_data = [np.loadtxt("reps/guitar_centroid.txt"), np.loadtxt("reps/clarinet_centroid.txt"), np.loadtxt("reps/flute_centroid.txt"), np.loadtxt("reps/saxophone_centroid.txt"), np.loadtxt("reps/violin_centroid.txt")]

scf_inp = []
scf_inputs = []
scf_outputs = []
for i in range(50):
    for j in range(5):
        scf_inputs = []
        scf_output = [0]*5
        scf_inputs.append(sc_data[j][i]/fund_data[j][i])
        scf_output[j] = 1
        scf_outputs.append(scf_output)
        scf_inp.append(scf_inputs)

scf_inp = np.array(scf_inp)
print(scf_inp.T)
scf_out = np.array(scf_outputs)
nn.initialize_network(scf_inp.T.shape[0], scf_out.T.shape[0], 2, 5)
nn.train_network(scf_inp.T, scf_out.T, nn.update_weights, 300, 0.01)
real = nn.predict_network(scf_inp.T, nn.logistic)
cm = confusion_matrix(real.T, scf_out, scf_out.T.shape[0])
print(cm)
print_cc_info(cm, 50, instrs)

[[ 18.92752262   7.88884833   4.49097417   7.27959114   6.18811563
   22.00265756   9.92023762   3.80928894  11.59891018   8.04488065
    5.24462538   4.99461998   3.53513668   4.85866566   7.70695139
   10.06204734   5.59984819   4.84177242   5.60320447   9.08678178
    5.08060445   8.98997568   3.3665418    7.64854568  10.49365173
    4.87543073  10.63547157   5.51381158  12.18021671   7.90011125
   18.68619502   5.40551524   4.10566039   5.22179945   9.1452648
   20.17346928   5.7859692    3.75442066   5.45092847   8.55642258
    5.89116535   9.94159384   5.70287813   4.66680682   9.88955929
    9.36926729  11.32183952   3.77446078   8.63229486   7.94697355
    5.79953339   5.99261568   4.90114013  13.2520959    9.68957425
    4.78587068   6.60506861   4.27260624   5.85398554  10.48093983
   15.60482643   9.09670745   4.32787124   8.07321513  10.08294096
   18.01490839  11.73731387   5.11066984  12.68114894  10.44293692
    8.48522415   5.69513658   4.28798934   6.94951966   9.50691

In [10]:
fund_data = [np.loadtxt("reps/guitar_funds.txt"), np.loadtxt("reps/clarinet_funds.txt"), np.loadtxt("reps/flute_funds.txt"), np.loadtxt("reps/saxophone_funds.txt"), np.loadtxt("reps/violin_funds.txt")]
sc_data = [np.loadtxt("reps/guitar_centroid.txt"), np.loadtxt("reps/clarinet_centroid.txt"), np.loadtxt("reps/flute_centroid.txt"), np.loadtxt("reps/saxophone_centroid.txt"), np.loadtxt("reps/violin_centroid.txt")]
zcr_data = [np.loadtxt("reps/guitar_zcr.txt"), np.loadtxt("reps/clarinet_zcr.txt"), np.loadtxt("reps/flute_zcr.txt"), np.loadtxt("reps/saxophone_zcr.txt"), np.loadtxt("reps/violin_zcr.txt")]

scfz_inp = []
scfz_inputs = []
scfz_outputs = []
for i in range(50):
    for j in range(5):
        scfz_inputs = []
        scfz_output = [0]*5
        scfz_inputs.append(sc_data[j][i]/fund_data[j][i])
        scfz_inputs.append(zcr_data[j][i])
        scfz_output[j] = 1
        scfz_outputs.append(scfz_output)
        scfz_inp.append(scfz_inputs)

scfz_inp = np.array(scfz_inp)
print(scfz_inp.T)
scfz_out = np.array(scfz_outputs)
nn.initialize_network(scfz_inp.T.shape[0], scfz_out.T.shape[0], 2, 5)
nn.train_network(scfz_inp.T, scfz_out.T, nn.update_weights, 300, 0.01)
real = nn.predict_network(scfz_inp.T, nn.logistic)
cm = confusion_matrix(real.T, scfz_out, scfz_out.T.shape[0])
print(cm)
print_cc_info(cm, 50, instrs)

[[  1.89275226e+01   7.88884833e+00   4.49097417e+00   7.27959114e+00
    6.18811563e+00   2.20026576e+01   9.92023762e+00   3.80928894e+00
    1.15989102e+01   8.04488065e+00   5.24462538e+00   4.99461998e+00
    3.53513668e+00   4.85866566e+00   7.70695139e+00   1.00620473e+01
    5.59984819e+00   4.84177242e+00   5.60320447e+00   9.08678178e+00
    5.08060445e+00   8.98997568e+00   3.36654180e+00   7.64854568e+00
    1.04936517e+01   4.87543073e+00   1.06354716e+01   5.51381158e+00
    1.21802167e+01   7.90011125e+00   1.86861950e+01   5.40551524e+00
    4.10566039e+00   5.22179945e+00   9.14526480e+00   2.01734693e+01
    5.78596920e+00   3.75442066e+00   5.45092847e+00   8.55642258e+00
    5.89116535e+00   9.94159384e+00   5.70287813e+00   4.66680682e+00
    9.88955929e+00   9.36926729e+00   1.13218395e+01   3.77446078e+00
    8.63229486e+00   7.94697355e+00   5.79953339e+00   5.99261568e+00
    4.90114013e+00   1.32520959e+01   9.68957425e+00   4.78587068e+00
    6.60506861e+00  

In [11]:
fund_data = [np.loadtxt("reps/guitar_funds.txt"), np.loadtxt("reps/clarinet_funds.txt"), np.loadtxt("reps/flute_funds.txt"), np.loadtxt("reps/saxophone_funds.txt"), np.loadtxt("reps/violin_funds.txt")]
sc_data = [np.loadtxt("reps/guitar_centroid.txt"), np.loadtxt("reps/clarinet_centroid.txt"), np.loadtxt("reps/flute_centroid.txt"), np.loadtxt("reps/saxophone_centroid.txt"), np.loadtxt("reps/violin_centroid.txt")]
zcr_data = [np.loadtxt("reps/guitar_zcr.txt"), np.loadtxt("reps/clarinet_zcr.txt"), np.loadtxt("reps/flute_zcr.txt"), np.loadtxt("reps/saxophone_zcr.txt"), np.loadtxt("reps/violin_zcr.txt")]

scfz_inp = []
scfz_inputs = []
scfz_outputs = []
for i in range(50):
    for j in range(5):
        scfz_inputs = []
        scfz_output = [0]*5
        scfz_inputs.append(sc_data[j][i]/(fund_data[j][i]))
        scfz_inputs.append(zcr_data[j][i])
        scfz_inputs.append(f_data[j][i][0]/np.max(np.array(f_data[j][i])))
        scfz_output[j] = 1
        scfz_outputs.append(scfz_output)
        scfz_inp.append(scfz_inputs)

scfz_inp = np.array(scfz_inp)
print(scfz_inp.T)
scfz_out = np.array(scfz_outputs)
nn.initialize_network(scfz_inp.T.shape[0], scfz_out.T.shape[0], 2, 5)
nn.train_network(scfz_inp.T, scfz_out.T, nn.update_weights, 300, 0.01)
real = nn.predict_network(scfz_inp.T, nn.logistic)
cm = confusion_matrix(real.T, scfz_out, scfz_out.T.shape[0])
print(cm)
print_cc_info(cm, 50, instrs)

[[  1.89275226e+01   7.88884833e+00   4.49097417e+00   7.27959114e+00
    6.18811563e+00   2.20026576e+01   9.92023762e+00   3.80928894e+00
    1.15989102e+01   8.04488065e+00   5.24462538e+00   4.99461998e+00
    3.53513668e+00   4.85866566e+00   7.70695139e+00   1.00620473e+01
    5.59984819e+00   4.84177242e+00   5.60320447e+00   9.08678178e+00
    5.08060445e+00   8.98997568e+00   3.36654180e+00   7.64854568e+00
    1.04936517e+01   4.87543073e+00   1.06354716e+01   5.51381158e+00
    1.21802167e+01   7.90011125e+00   1.86861950e+01   5.40551524e+00
    4.10566039e+00   5.22179945e+00   9.14526480e+00   2.01734693e+01
    5.78596920e+00   3.75442066e+00   5.45092847e+00   8.55642258e+00
    5.89116535e+00   9.94159384e+00   5.70287813e+00   4.66680682e+00
    9.88955929e+00   9.36926729e+00   1.13218395e+01   3.77446078e+00
    8.63229486e+00   7.94697355e+00   5.79953339e+00   5.99261568e+00
    4.90114013e+00   1.32520959e+01   9.68957425e+00   4.78587068e+00
    6.60506861e+00  