In [2]:
import neural_net as nn
import numpy as np

In [3]:
weights = nn.initialize_network(2, 1, 2, 2)
print(weights)
# print(np.array(weights))

[array([[-1.0856306 ,  0.99734545],
       [ 0.2829785 , -1.50629471]]), array([[-2.42667924, -0.42891263]])]


In [27]:
#Confusion matrix
instrs = ["guitar", "clarinet", "flute", "saxophone", "violin"]

def confusion_matrix (actual, desired, outp_length):
    """Gets confusion matrix for a networks output."""
    confusion = np.zeros((outp_length, outp_length))
    for indx in range(len(actual)):
        # print(desired[indx])
        i = desired[indx].tolist().index(1)
        # print(actual[indx])
        j = actual[indx].argmax()
        confusion[i][j] += 1
    return confusion

def print_cc_info(cc, data_length, categories):
    sum1, sum2 = 0, 0
    class_list = []
    for i in range(len(cc)):
        for j in range(len(cc[i])):
            if j == i: 
                sum1 += cc[i][j]
                class_list.append(cc[i][j])
            sum2 += cc[i][j]
    print("This NN got correct ", sum1, " out of ", sum2, " tests")
    print("which is ", str(sum1/sum2)[:5])
    for i in range(len(categories)):
        print("For", categories[i], ", This NN classified", class_list[i], " out of ", data_length)
        print("which is ", str(class_list[i]/data_length)[:5])

Testing the neural network on the data from ps6. Looks like it does pretty well!

In [25]:
def load_data(filename):
    data = np.loadtxt(filename,delimiter=',')
    inputs = []
    outputs = []
    for line in data:
        inputs.append(line[:-1])
        output = [0] * 10
        output[int(line[-1])] = 1
        outputs.append(output)
    return (np.array(inputs), np.array(outputs))

(test_inp, test_out) = load_data("data/optdigits.tra")

nn.initialize_network(test_inp.T.shape[0], test_out.T.shape[0], 2, 10)
nn.train_network(test_inp.T, test_out.T, nn.update_weights, 50, 0.01)
actual = nn.predict_network(test_inp.T, nn.logistic)
cc = confusion_matrix(actual.T, test_out, test_out.T.shape[0])
print(cc)




Iteration:  0
Iteration:  1
Iteration:  2
Iteration:  3
Iteration:  4
Iteration:  5
Iteration:  6
Iteration:  7
Iteration:  8
Iteration:  9
Iteration:  10
Iteration:  11
Iteration:  12
Iteration:  13
Iteration:  14
Iteration:  15
Iteration:  16
Iteration:  17
Iteration:  18
Iteration:  19
Iteration:  20
Iteration:  21
Iteration:  22
Iteration:  23
Iteration:  24
Iteration:  25
Iteration:  26
Iteration:  27
Iteration:  28
Iteration:  29
Iteration:  30
Iteration:  31
Iteration:  32
Iteration:  33
Iteration:  34
Iteration:  35
Iteration:  36
Iteration:  37
Iteration:  38
Iteration:  39
Iteration:  40
Iteration:  41
Iteration:  42
Iteration:  43
Iteration:  44
Iteration:  45
Iteration:  46
Iteration:  47
Iteration:  48
Iteration:  49
[[ 366.    1.    0.    0.    0.    1.    3.    0.    0.    5.]
 [   0.  337.   18.    1.    1.    6.    4.    3.    7.   12.]
 [   2.    0.  355.    4.    0.    0.    5.    0.    0.   14.]
 [   0.   10.   10.  361.    0.    1.    0.    1.    1.    5.]
 [   0. 

Testing the neural network on the harmonic information. Looks like it can classify guitars pretty well based on the harmonic information, but not very well for the other instruments. 

In [30]:
h_data = []
instrs = ["guitar", "clarinet", "flute", "saxophone", "violin"]
ind = 0
for instr in instrs:
    h_data.append([])
    infile = open("reps/" + instr + "_harmonics.txt", 'r')
    for line in infile:
        ex = []
        for i in line.split(','):
            ex.append( float(i.strip()) )
        h_data[ind].append(ex)
    ind += 1
        
#print(h_data)
h_inp = []
h_outputs = []
for i in range(50):
    for j in range(5):
        h_output = [0]*5
        h_output[j] = 1
        h_outputs.append(h_output)
        h_inp.append(np.array(h_data[j][i]))

h_inp = np.array(h_inp)
h_out = np.array(h_outputs)

nn.initialize_network(h_inp.T.shape[0], h_out.T.shape[0], 2, 5)
nn.train_network(h_inp.T, h_out.T, nn.update_weights, 50, 0.01)
real = nn.predict_network(h_inp.T, nn.logistic)
cm = confusion_matrix(real.T, h_out, h_out.T.shape[0])
print(cm)
print_cc_info(cm, 50, instrs)

Iteration:  0
Iteration:  1
Iteration:  2
Iteration:  3
Iteration:  4
Iteration:  5
Iteration:  6
Iteration:  7
Iteration:  8
Iteration:  9
Iteration:  10
Iteration:  11
Iteration:  12
Iteration:  13
Iteration:  14
Iteration:  15
Iteration:  16
Iteration:  17
Iteration:  18
Iteration:  19
Iteration:  20
Iteration:  21
Iteration:  22
Iteration:  23
Iteration:  24
Iteration:  25
Iteration:  26
Iteration:  27
Iteration:  28
Iteration:  29
Iteration:  30
Iteration:  31
Iteration:  32
Iteration:  33
Iteration:  34
Iteration:  35
Iteration:  36
Iteration:  37
Iteration:  38
Iteration:  39
Iteration:  40
Iteration:  41
Iteration:  42
Iteration:  43
Iteration:  44
Iteration:  45
Iteration:  46
Iteration:  47
Iteration:  48
Iteration:  49
[[ 11.   6.  31.   0.   2.]
 [  0.  50.   0.   0.   0.]
 [  3.  39.   3.   0.   5.]
 [  0.  47.   1.   0.   2.]
 [  0.  39.   1.   0.  10.]]
This NN got correct  74.0  out of  250.0  tests
which is  0.296
For guitar , This NN classified 11.0  out of  50
which 

Now testing the neural network on the spectral flux. It does decently well, getting around 50% correct across all instruments. It is especially bad at classifying the saxophone (it usually classifies it as a violin), which makes sense given that the spectrum for both instruments looks quite similar (aside from the attack portion of the spectrum). 

In [52]:
f_data = []
instrs = ["guitar", "clarinet", "flute", "saxophone", "violin"]
ind = 0
for instr in instrs:
    f_data.append([])
    infile = open("reps/" + instr + "_flux.txt", 'r')
    for line in infile:
        ex = []
        for i in line.split(','):
            ex.append( float(i.strip()) )
        f_data[ind].append(ex)
    ind += 1
        
#print(h_data)
f_inp = []
f_outputs = []
for i in range(50):
    for j in range(5):
        f_output = [0]*5
        f_output[j] = 1
        f_outputs.append(f_output)
        f_inp.append(np.array(f_data[j][i]))

f_inp = np.array(f_inp)
f_out = np.array(f_outputs)

nn.initialize_network(f_inp.T.shape[0], f_out.T.shape[0], 2, 5)
nn.train_network(f_inp.T, f_out.T, nn.update_weights, 500, 0.01)
real = nn.predict_network(f_inp.T, nn.logistic)
cm = confusion_matrix(real.T, f_out, f_out.T.shape[0])
print(cm)
print_cc_info(cm, 50, instrs)

Iteration:  0
Iteration:  1
Iteration:  2
Iteration:  3
Iteration:  4
Iteration:  5
Iteration:  6
Iteration:  7
Iteration:  8
Iteration:  9
Iteration:  10
Iteration:  11
Iteration:  12
Iteration:  13
Iteration:  14
Iteration:  15
Iteration:  16
Iteration:  17
Iteration:  18
Iteration:  19
Iteration:  20
Iteration:  21
Iteration:  22
Iteration:  23
Iteration:  24
Iteration:  25
Iteration:  26
Iteration:  27
Iteration:  28
Iteration:  29
Iteration:  30
Iteration:  31
Iteration:  32
Iteration:  33
Iteration:  34
Iteration:  35
Iteration:  36
Iteration:  37
Iteration:  38
Iteration:  39
Iteration:  40
Iteration:  41
Iteration:  42
Iteration:  43
Iteration:  44
Iteration:  45
Iteration:  46
Iteration:  47
Iteration:  48
Iteration:  49
Iteration:  50
Iteration:  51
Iteration:  52
Iteration:  53
Iteration:  54
Iteration:  55
Iteration:  56
Iteration:  57
Iteration:  58
Iteration:  59
Iteration:  60
Iteration:  61
Iteration:  62
Iteration:  63
Iteration:  64
Iteration:  65
Iteration:  66
Itera

Now testing the neural network on the zero-crossing rate and spectral centroid. It does pretty poorly. 

In [39]:
zcr_data = [np.loadtxt("reps/guitar_zcr.txt"), np.loadtxt("reps/clarinet_zcr.txt"), np.loadtxt("reps/flute_zcr.txt"), np.loadtxt("reps/saxophone_zcr.txt"), np.loadtxt("reps/violin_zcr.txt")]
sc_data = [np.loadtxt("reps/guitar_centroid.txt"), np.loadtxt("reps/clarinet_centroid.txt"), np.loadtxt("reps/flute_centroid.txt"), np.loadtxt("reps/saxophone_centroid.txt"), np.loadtxt("reps/violin_centroid.txt")]

zc_inp = []
zc_inputs = []
zc_outputs = []
for i in range(50):
    for j in range(5):
        zc_inputs = []
        zc_output = [0]*5
        zc_inputs.append(sc_data[j][i])
        zc_inputs.append(zcr_data[j][i])
        zc_output[j] = 1
        zc_outputs.append(zc_output)
        zc_inp.append(zc_inputs)

zc_inp = np.array(zc_inp)
print(zc_inp.T)
zc_out = np.array(zc_outputs)
nn.initialize_network(zc_inp.T.shape[0], zc_out.T.shape[0], 2, 5)
nn.train_network(zc_inp.T, zc_out.T, nn.update_weights, 50, 0.01)
real = nn.predict_network(zc_inp.T, nn.logistic)
cm = confusion_matrix(real.T, zc_out, zc_out.T.shape[0])
print(cm)
print_cc_info(cm, 50, instrs)

[[  2.08202749e+03   1.73554663e+03   1.97602863e+03   1.60151005e+03
    1.36138544e+03   2.42029233e+03   2.18245228e+03   1.67608714e+03
    2.55176024e+03   1.76987374e+03   1.15381758e+03   1.09881640e+03
    1.55546014e+03   1.06890645e+03   1.69552931e+03   2.21365041e+03
    1.23196660e+03   2.13037987e+03   1.23270498e+03   1.99909199e+03
    2.23546596e+03   1.97779465e+03   1.48127839e+03   1.68268005e+03
    2.30860338e+03   2.14518952e+03   2.33980374e+03   2.42607709e+03
    2.67964768e+03   1.73802448e+03   2.17768917e+03   1.18921335e+03
    1.80649057e+03   1.14879588e+03   2.01195826e+03   2.35101611e+03
    1.27291322e+03   1.65194509e+03   1.19920426e+03   1.88241297e+03
    1.37311282e+03   2.18715065e+03   2.50926638e+03   1.02669750e+03
    2.17570304e+03   2.18378882e+03   2.49080469e+03   1.66076274e+03
    1.89910487e+03   1.74833418e+03   2.70351049e+03   1.31837545e+03
    2.15650166e+03   2.91546110e+03   2.13170634e+03   2.23098148e+03
    1.45311509e+03  

Testing the neural network on the ratio of spectral centroid to zero-crossing rate. Still does pretty poorly.

In [42]:
r_inp = []
r_inputs = []
r_outputs = []
for i in range(50):
    for j in range(5):
        r_inputs = []
        r_output = [0]*5
        r_inputs.append(sc_data[j][i]/zcr_data[j][i])
        r_output[j] = 1
        r_outputs.append(r_output)
        r_inp.append(r_inputs)

r_inp = np.array(r_inp)
print(r_inp.T)
r_out = np.array(r_outputs)
nn.initialize_network(zc_inp.T.shape[0], zc_out.T.shape[0], 2, 5)
nn.train_network(zc_inp.T, zc_out.T, nn.update_weights, 50, 0.01)
real = nn.predict_network(zc_inp.T, nn.logistic)
cm = confusion_matrix(real.T, zc_out, zc_out.T.shape[0])
print(cm)
print_cc_info(cm, 50, instrs)

[[  21009.38791752   53024.87555951   80886.77620302   74997.5438002
    72944.93146404   56600.47120614   47714.46030232   97983.55359226
    69167.7128654   118770.55643017   11031.06904368   47158.61423894
   156572.91979698   45050.49603522  129191.32280729   25827.29034741
    51608.20090019  229364.26218276   61475.15766608   79573.61289492
    17286.99497752   57913.94721851   81858.39563639   69943.97895065
   137054.5595292    42607.90224218   43537.02283948   61665.52683315
    61621.70775747  116069.80846881   35250.13698092   44935.14010475
    68302.01893393   54016.8511593   114329.75350818   24690.98202721
    48465.63164369   79040.03086901   59100.89037862  130334.229843
    19042.32173093   48854.9414697   158828.28933901   45490.59697447
   117182.80084402   65596.76864103   49582.13260633   97799.29345531
    93788.86409942  115628.14687429   23361.8033048    49692.4261464
    57830.22101223   51885.85311558   89521.06938611   40699.22888441
    51747.13328028   614

In [ ]:
zcr_data = [np.loadtxt("reps/guitar_zcr.txt"), np.loadtxt("reps/clarinet_zcr.txt"), np.loadtxt("reps/flute_zcr.txt"), np.loadtxt("reps/saxophone_zcr.txt"), np.loadtxt("reps/violin_zcr.txt")]
sc_data = [np.loadtxt("reps/guitar_centroid.txt"), np.loadtxt("reps/clarinet_centroid.txt"), np.loadtxt("reps/flute_centroid.txt"), np.loadtxt("reps/saxophone_centroid.txt"), np.loadtxt("reps/violin_centroid.txt")]

zc_inp = []
zc_inputs = []
zc_outputs = []
for i in range(50):
    for j in range(5):
        zc_inputs = []
        zc_output = [0]*5
        zc_inputs.append(sc_data[j][i])
        zc_inputs.append(zcr_data[j][i])
        zc_output[j] = 1
        zc_outputs.append(zc_output)
        zc_inp.append(zc_inputs)

zc_inp = np.array(zc_inp)
print(zc_inp.T)
zc_out = np.array(zc_outputs)
nn.initialize_network(zc_inp.T.shape[0], zc_out.T.shape[0], 2, 5)
nn.train_network(zc_inp.T, zc_out.T, nn.update_weights, 50, 0.01)
real = nn.predict_network(zc_inp.T, nn.logistic)
cm = confusion_matrix(real.T, zc_out, zc_out.T.shape[0])
print(cm)
print_cc_info(cm, 50, instrs)